name: Deploy Static Website to EC2 
 
on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: Zip Static Files
    - name: Zip Static Files
      run: |
        echo "Zipping files for EC2 deployment..."
        zip -r static-website.zip .
        echo "Files zipped successfully."

    # Step 4: Copy ZIP File to EC2 Instance
    - name: Copy Files to EC2
      run: |
        echo "Copying files to EC2 instance..."
        scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY_PAIR_PATH }} static-website.zip ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/
        echo "Files copied successfully."

    # Step 5: Deploy Static Website on EC2
    - name: Deploy on EC2
      run: |
        echo "Deploying on EC2 instance..."
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY_PAIR_PATH }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          cd /var/www/html
          sudo unzip -o /home/ec2-user/static-website.zip -d .
          sudo chmod -R 755 /var/www/html
          echo "Static website deployed successfully on EC2."
        EOF
